import streamlit as st
import os
from datetime import datetime, timedelta
from main_waf import main_waf
from main_bot import main_bot

# --- Page Configuration ---
st.set_page_config(
    page_title="Radware Autoreport", 
    page_icon="🌐", 
    layout="centered",
    initial_sidebar_state="collapsed"
)

# --- Custom CSS ---
st.markdown("""
    <style>
    /* Background and Font */
    .main { background-color: #f8f9fa; }
    
    /* Image Quality Enhancement */
    img {
        image-rendering: -webkit-optimize-contrast;
        image-rendering: crisp-edges;
    }

    /* Configuration Card Style */
    div.stBlock {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 15px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        margin-bottom: 10px;
    }

    /* 
       MAIN BUTTON (GENERATE JSON) - ULTRA FORCE WHITE TEXT 
       Apuntamos a todas las capas posibles del botón para que no haya duda
    */
    .stButton>button {
        background: linear-gradient(90deg, #1c5573 0%, #2a7da9 100%) !important;
        border: none !important;
        border-radius: 8px !important;
        padding: 0.6rem 2rem !important;
        width: 100% !important;
        transition: all 0.3s ease !important;
    }

    /* Selector específico para el texto dentro del botón */
    .stButton>button, .stButton>button p, .stButton>button div, .stButton>button span {
        color: white !important;
        font-weight: normal !important;
        text-decoration: none !important;
    }
    
    /* Hover state */
    .stButton>button:hover {
        transform: translateY(-2px) !important;
        box-shadow: 0 5px 15px rgba(28, 85, 115, 0.3) !important;
    }

    .stButton>button:hover p, .stButton>button:hover div {
        color: white !important;
    }

    /* Power BI Download Buttons Style (Secondary) */
    div[data-testid="stVerticalBlock"] > div:has(button[kind="secondary"]) button {
        border: 1px solid #f2c811 !important;
        color: #333 !important;
        background-color: #fff !important;
    }
    div[data-testid="stVerticalBlock"] > div:has(button[kind="secondary"]) button:hover {
        background-color: #f2c811 !important;
        color: #000 !important;
    }

    /* Titles and Header text */
    h1 { color: #1c5573; font-weight: 800 !important; margin-bottom: 0px !important; }
    h3 { color: #495057; font-size: 1.2rem !important; margin-top: 0px !important; margin-bottom: 1rem !important; }
    
    .stTextInput>div>div>input {
        border-radius: 8px;
    }

    .header-text-container {
        margin-bottom: 15px;
    }
    </style>
    """, unsafe_allow_html=True)

# --- Header Section ---
col_logo, col_title = st.columns([1, 4])

with col_logo:
    st.image("logo_radware.png", width=200)

with col_title:
    st.markdown("""
        <div style='padding-top: 28px; margin-left: 80px;' class='header-text-container'>
            <h1>AUTOREPORT</h1>
            <p style='margin-top:-15px; color:gray; font-size:1.1rem;'>Cloud Security Reporting Tool</p>
        </div>
        """, unsafe_allow_html=True)

# --- Configuration Form ---
with st.container():
    st.markdown("### 🛠️ Configuration")
    
    col1, col2 = st.columns(2)
    with col1:
        domain = st.text_input("Application (Domain)", placeholder="example.com")
        account_id = st.text_input("Account ID", placeholder="Enter Account ID")
    
    with col2:
        x_api_key = st.text_input("X-API-KEY", type="password", placeholder="Secret key")
        service = st.selectbox("Security Service", ["WAF", "BOT"])

    st.markdown("---")
    st.markdown("### 📅 Time Range & Filters")
    
    col3, col4 = st.columns(2)
    dias_max = 30 if service == "WAF" else 7
    fecha_minima = datetime.now() - timedelta(days=dias_max)
    
    with col3:
        start_date = st.date_input("Start Date", value=datetime.now() - timedelta(days=1), min_value=fecha_minima)
    with col4:
        end_date = st.date_input("End Date", value=datetime.now())

    only_blocked = st.toggle("Only Blocked Events", value=True)

# --- Power BI Download Section ---
st.markdown("<br>", unsafe_allow_html=True)
with st.expander("📊 Download Power BI Dashboards (.pbix)", expanded=False):
    st.info("Download these templates to visualize the JSON data generated by this tool.")
    pbi_col1, pbi_col2 = st.columns(2)
    
    pbi_waf_file = "CWAAP_AutoReport.pbix"
    pbi_bot_file = "BOTM_AutoReport.pbix"

    with pbi_col1:
        if os.path.exists(pbi_waf_file):
            with open(pbi_waf_file, "rb") as f:
                st.download_button(
                    label="📊 Download WAF PBIX",
                    data=f,
                    file_name="Radware_WAF_Dashboard.pbix",
                    mime="application/octet-stream",
                    use_container_width=True
                )
        else:
            st.caption("WAF template file not found")

    with pbi_col2:
        if os.path.exists(pbi_bot_file):
            with open(pbi_bot_file, "rb") as f:
                st.download_button(
                    label="🤖 Download BOT PBIX",
                    data=f,
                    file_name="Radware_BOT_Dashboard.pbix",
                    mime="application/octet-stream",
                    use_container_width=True
                )
        else:
            st.caption("BOT template file not found")

# --- Execution Logic ---
st.markdown("<br>", unsafe_allow_html=True)
if st.button("GENERATE JSON", use_container_width=True):
    if not domain or not x_api_key or not account_id:
        st.warning("⚠️ Please fill in all the required fields before proceeding.")
    else:
        config = {
            "domain": domain,
            "x_api_key": x_api_key,
            "account_id": account_id,
            "start": f"{start_date} 00:00:00",
            "end": f"{end_date} 23:59:59",
            "service": service,
            "only_blocked": "y" if only_blocked else "n"
        }

        try:
            with st.spinner(f"Connecting to Radware Cloud for {domain}..."):
                if service == "WAF":
                    main_waf(config)
                    generated_file = f"{domain}.json"
                else:
                    main_bot(config)
                    generated_file = f"{domain}_bot.json"

            if os.path.exists(generated_file):
                st.balloons()
                st.success(f"✨ Report for {domain} is ready!")
                
                with open(generated_file, "rb") as f:
                    st.download_button(
                        label="⬇️ Download JSON Report",
                        data=f,
                        file_name=generated_file,
                        mime="application/json"
                    )
            else:
                st.error("❌ File was not created. Please check API logs and connectivity.")
                
        except Exception as e:
            st.error(f"❌ Critical Error: {str(e)}")

# --- Footer ---
st.markdown("<br><br>", unsafe_allow_html=True)
st.markdown("---")
footer_col1, footer_col2 = st.columns([3,1])
with footer_col1:
    st.caption("© 2026 Radware CALA TAM - Technical Internal Tool")
with footer_col2:
    st.caption(f"Author | **Nicolas Pedraza**")
